name: repaircar
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  giffy_dialog: ^1.7.0
  package_info: ^0.4.0+16
  dio: ^3.0.8
  shared_preferences: ^0.5.6+2
  firebase_messaging: ^6.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

